### ISSUE TITLE
titlepage.svg issues

### ISSUE THREAD

**Issue by acabal** [SSteve/f-scott-fitzgerald_this-side-of-paradise#1]
titlepage.svg must have its height exactly fit the contents plus some padding. See our art manual for more details. You can copy and paste the viewbox from a different work with the same title dimensions.

Once that's fixed, make sure to run `build-images` again.

**Comment by SSteve** [comment]
Done. I used the viewbox from https://github.com/standardebooks/j-sheridan-le-fanu_uncle-silas.git
