### ISSUE TITLE
content.opf issues

### ISSUE THREAD

**Issue by acabal** [SSteve/f-scott-fitzgerald_this-side-of-paradise#10]
- The long-description must be escaped HTML. See any other content.opf file for an example of what it should look like.
- The long-description should also aim to be slightly more encyclopedic. Can you include more information about the book's publication history, reception, and impact? (In your own words--no copy and paste from Wikipedia)

**Comment by SSteve** [comment]
I hope this is sufficient. Believe it or not, I spent hours on this. It turns out I'm not good at writing book descriptions.
