### ISSUE TITLE
Part headers to Roman

### ISSUE THREAD

**Issue by acabal** [SSteve/f-scott-fitzgerald_this-side-of-paradise#11]
For book 1 and 2, please use Roman numerals for "one" and "two", with a semantic span. For example:
````
<h2 epub:type="title">Book <span epub:type="z3998:roman">I</span>
	<span epub:type="subtitle">The Romantic Egotist</span>
</h2>
````

Note that the ToC should be updated to Roman, and the `<title>` tags should be changed to Decimal numbers instead of spelling out "one", "two".

**Comment by SSteve** [comment]
Done
