### ISSUE TITLE
Miscurled quotation marks

### ISSUE THREAD

**Issue by acabal** [SSteve/f-scott-fitzgerald_this-side-of-paradise#2]
Use this regex to find quotation marks that should be reviewed: `\s‘[a-z]`

For example in `chapter-1-1.xhtml`: `<p>“ ‘Lo, Amory.”</p>` The single quote is curled in the wrong direction. Because that is an elision, it should a right single quote, not a left single quote. There are at least several other instances of this issue in the text.

**Comment by SSteve** [comment]
Done
