### ISSUE TITLE
Titles of books not italicized

### ISSUE THREAD

**Issue by acabal** [SSteve/f-scott-fitzgerald_this-side-of-paradise#3]
Using the same regex: `\s‘[a-z]` I see more than a few titles of books that are quoted, instead of being italicized per our typography manual.

For example in `chapter-1-2.xhtml`: `<p>“Yes, that’s the fella. I’ve just finished a book of his, ‘The Picture of Dorian Gray,’ and I certainly...`

Because The Picture of Dorian Gray is a book, we italicize it instead of quoting it: `<i epub:type="se:name.publication.book">The Picture of Dorian Gray</i>`

There are a large number of instances of this in the book. They must all be reviewed and converted.

Not everything is italicized. For a list of what to italicize vs what to set in quotation marks, see the typography manual.

**Comment by SSteve** [comment]
Done
