### ISSUE TITLE
local.css issues

### ISSUE THREAD

**Issue by acabal** [SSteve/f-scott-fitzgerald_this-side-of-paradise#4]
- line 8, `b` is missing `font-weight: normal;`
- In `chapter-1-1.xhtml`, use `<td>` instead of `<th>`. Because we have a `<thead>` tag, the child cells are implicitly the headers. Then you can target them for style with `thead td`.
- Instead of having `<p class="title">`, use the following structure: `<header><p>The title...</p></header>` and target `header p`.  `<header>` is OK to use in sectioning content like `<blockquote>` and that's the preferred way of stying headers that don't appear in the ToC.
- Style: please put a space between properties and their values (ex. line 83, 87, etc.)

**Comment by SSteve** [comment]
@acabal Sorry, I'm not sure what you mean by `b` is missing `font-weight: normal;`. Here's that section of local.css:

```
b{
	font-weight: normal;
}
```

**Comment by acabal** [comment]
Ah, sorry, my mistake. Not sure what I was thinking there.

**Comment by SSteve** [comment]
Done.
