### ISSUE TITLE
<i> missing semantics

### ISSUE THREAD

**Issue by acabal** [SSteve/f-scott-fitzgerald_this-side-of-paradise#5]
There are more than a few instances of `<i>` being used without semantics. When referring to books, journals, newspapers, etc., please include the relevant `epub:type` se attribute. For example, `the <i epub:type="se:name.publication.newspaper">Princetonian</i>`. You can read the vocabulary here: https://standardebooks.org/vocab/1.0

**Comment by SSteve** [comment]
@acabal There are a couple places where he abbreviated *Princetonian* to *Prince*. I wrapped those in `abbr` tags like this:

`<i epub:type="se:name.publication.newspaper"><abbr class="contraction">Prince</abbr></i>`

Is that correct?

**Comment by SSteve** [comment]
@acabal How about when he abbreviates *Nassau Literary Magazine* to *Nassau Lit.*? Do I put `abbr` around just *Lit.*?

**Comment by acabal** [comment]
Re. _Prince_, I don't think it's necessary to put an `<abbr>` tag there, since there's no period or apostrophe. But yes, for "Lit." you can just wrap it in `<abbr>` without any class.

**Comment by SSteve** [comment]
@acabal He he uses “Lit.” at the end of a sentence. Would I make that `<abbr class=“eoc”>`?

**Comment by acabal** [comment]
Yes exactly!

**Comment by SSteve** [comment]
@acabal A last couple `<i>` tags without semantics:

`<p>“Now, Langueduc, if I used that formula, where would my <i>A</i> point be?”</p>`

`They wore black armbands with orange “<i>P</i>’s,”`

Is `<i>` without semantics correct for these?

**Comment by acabal** [comment]
Yes, per the typography manual that is one of the very few cases where unsemantic `<i>` is correct :)

**Comment by SSteve** [comment]
Done.
