### ISSUE TITLE
Run modernize-spelling again

### ISSUE THREAD

**Issue by acabal** [SSteve/f-scott-fitzgerald_this-side-of-paradise#6]
You were working on an extremely old branch of the toolset, and `modernize-spelling` underwent a lot of changes since you started. Please run it again and review the changes with `git difftool` to ensure they're correct. (They will most likely all be correct, the only thing you have to watch out for is sometimes removing dashes in words makes a new, incorrect word for the context; but this is also very rare.)

When committing this update remember to precede the commit message with `[Editorial]`

**Comment by SSteve** [comment]
Done.

In chapter 1-2: Left "cut-in" as-is. "Cutin" is a waxy substance. Left "da-da'd" as-is. They were singing "da-da" (and pre-dated dadaism).
