### ISSUE TITLE
Additional <section> tags required

### ISSUE THREAD

**Issue by acabal** [SSteve/f-scott-fitzgerald_this-side-of-paradise#9]
Because this book is in the format of several "books" with chapters, we require that each chapter file contain wrapping `<section>` semantics for its direct "book" parents. For example, `chapter-1-1.xhtml` should begin: 

````
<body epub:type="bodymatter z3998:fiction">
		<section id="book-1" epub:type="part">
			<section id="chapter-1-1" epub:type="chapter">
````

This allows us to use the `recompose-epub` tool to merge all of the files into one structurally-correct HTML5 file. You can run that tool to check if you're doing the right thing. (Open the output in Firefox and use the developer tools to observe the structure it outputs. If everything is correct, then the chapters will be children of the book `<section>`s.)

**Comment by SSteve** [comment]
Done
